global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'connectflow'
    scheme: https
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:5001']  # For when running app outside Docker but monitoring in Docker
    scrape_interval: 5s                         # More frequent scraping for application metrics
    scrape_timeout: 3s                          # Shorter timeout to fail faster
    tls_config:
      insecure_skip_verify: true                # Skip certificate verification for development
    
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
