global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'connectflow'
    scheme: https
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:5001']  # For when running app outside Docker but monitoring in Docker
    scrape_interval: 2s                         # More frequent scraping for application metrics
    scrape_timeout: 1s                          # Shorter timeout to fail faster
    tls_config:
      insecure_skip_verify: true                # Skip certificate verification for development
      
  - job_name: 'connectflow-health'
    scheme: https
    metrics_path: /metrics/health
    static_configs:
      - targets: ['host.docker.internal:5001']  # For when running app outside Docker but monitoring in Docker
    scrape_interval: 5s                         # Health checks don't need to be as frequent
    scrape_timeout: 2s                          
    tls_config:
      insecure_skip_verify: true                # Skip certificate verification for development
    
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
      
  - job_name: 'rabbitmq-exporter'
    static_configs:
      - targets: ['rabbitmq-exporter:9419']
    scrape_interval: 5s
    scrape_timeout: 3s
    metrics_path: /metrics
    honor_labels: true
